---

- name: User workload monitoring
  ansible.builtin.include_tasks: user_workload_monitoring.yml

- name: Install OpenShift Gitops
  ansible.builtin.include_tasks: openshift_gitops.yml

- name: Install Globex AI app
  ansible.builtin.include_tasks: application.yml

- name: Install Showroom
  ansible.builtin.include_tasks: showroom.yml
